
-- Script para criar a tabela AD_CONTRATOS no Oracle
-- Execute este script no banco de dados Oracle FREEPDB1

-- Criar a tabela AD_CONTRATOS
CREATE TABLE AD_CONTRATOS (
    ID_EMPRESA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPRESA VARCHAR2(200) NOT NULL,
    CNPJ VARCHAR2(18) NOT NULL,
    SANKHYA_TOKEN VARCHAR2(500),
    SANKHYA_APPKEY VARCHAR2(500),
    SANKHYA_USERNAME VARCHAR2(200),
    SANKHYA_PASSWORD VARCHAR2(200),
    GEMINI_API_KEY VARCHAR2(500),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_contratos_cnpj UNIQUE (CNPJ)
);

-- Criar índices para melhorar performance
CREATE INDEX idx_contratos_empresa ON AD_CONTRATOS(EMPRESA);
CREATE INDEX idx_contratos_ativo ON AD_CONTRATOS(ATIVO);

-- Criar trigger para atualizar DATA_ATUALIZACAO automaticamente
CREATE OR REPLACE TRIGGER trg_contratos_atualizacao
BEFORE UPDATE ON AD_CONTRATOS
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

-- Comentários nas colunas
COMMENT ON TABLE AD_CONTRATOS IS 'Tabela de contratos de empresas que utilizam o sistema';
COMMENT ON COLUMN AD_CONTRATOS.ID_EMPRESA IS 'Identificador único da empresa';
COMMENT ON COLUMN AD_CONTRATOS.EMPRESA IS 'Nome da empresa';
COMMENT ON COLUMN AD_CONTRATOS.CNPJ IS 'CNPJ da empresa';
COMMENT ON COLUMN AD_CONTRATOS.SANKHYA_TOKEN IS 'Token de autenticação Sankhya';
COMMENT ON COLUMN AD_CONTRATOS.SANKHYA_APPKEY IS 'App Key do Sankhya';
COMMENT ON COLUMN AD_CONTRATOS.SANKHYA_USERNAME IS 'Usuário Sankhya';
COMMENT ON COLUMN AD_CONTRATOS.SANKHYA_PASSWORD IS 'Senha Sankhya';
COMMENT ON COLUMN AD_CONTRATOS.GEMINI_API_KEY IS 'Chave API do Google Gemini';
COMMENT ON COLUMN AD_CONTRATOS.ATIVO IS 'Indica se o contrato está ativo (S/N)';
COMMENT ON COLUMN AD_CONTRATOS.DATA_CRIACAO IS 'Data de criação do registro';
COMMENT ON COLUMN AD_CONTRATOS.DATA_ATUALIZACAO IS 'Data da última atualização';

-- Inserir um registro de exemplo (opcional)
-- INSERT INTO AD_CONTRATOS (EMPRESA, CNPJ, SANKHYA_TOKEN, SANKHYA_APPKEY, SANKHYA_USERNAME, SANKHYA_PASSWORD, GEMINI_API_KEY, ATIVO)
-- VALUES ('Empresa Exemplo', '12.345.678/0001-90', 'token_exemplo', 'appkey_exemplo', 'usuario@exemplo.com', 'senha123', 'gemini_key_exemplo', 'S');

COMMIT;
